spring.application.name=team-task-manager
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=taskmanager;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=Ks120@120

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secret=VGhpc0lzQVNlY3VyZUpXVFNlY3JldEtleUZvclRhc2tNYW5hZ2VyMjAyNg==
jwt.expiration=86400000

server.port=8080